id: app
title: Hologic New Product Introduction Workflow
type: project
version: 0.0.1
icon: app.png
protocol:
- govready.com/apps/compliance/2018/basic-system-description
interstitial:
  format: markdown
  template: |
    ## Prepare a Basic System Description

    We'll help you prepare a re-usable description of your information system

    - Set an official system name and nickname
    - Gather basic facts about the type of system

    Are you ready?
introduction:
  format: markdown
  template: |
    This project will guide you through giving your system a unique name and preparing basic system descriptions.
invitation_to_task_interstitial:
  format: markdown
  template: |
    ## Thanks for accepting {{invitation.from_user}}'s invitation

    You've been asked to help with {{task.title}} for {{project}}.

    We'll tell {{invitation.from_user}} you're getting started.
export_button_label: Export System Description and Control Information
output:
- id: system_profile
  tab: System Profile
  format: markdown
  template: |
    <div style="text-align:center;">

    ## Create a profile for your system

    ![](app.png)

    ### No sweat! We'll capture the details quickly.

    </div>
- id: system_name
  format: markdown
  template: |
    {{project.system_basics.system_name}}
- id: system_nickname
  format: markdown
  template: |
    {{project.system_basics.system_nickname}}
catalog:
  title: Prodsec - Build Product Profile
  category: System Information
  description:
    long: |
      New Compliance App
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
    short: Describe the product you are developing.
  source_url: https://github.com/GovReady/govready-q-files-starterpack/apps/Basic-System-Description
  status: Operational
  vendor: GovReady®
  vendor_url: http://www.govready.com
  version: 1.0.0
questions:
- id: system_basics
  title: Document official system name and type
  type: module
  module-id: system_name_and_details
  tab: System Profile
  group: System Description
- id: system_basics_technical
  title: Document basic technical details
  type: module
  module-id: system_basics_technical
  tab: System Profile
  group: System Description
- id: system_description
  title: Prepare re-usable system descriptions
  type: module
  module-id: system_description
  tab: System Profile
  group: System Description
